const mediaBaseUrl = "https://martin-motion-media.martinbarbe09.workers.dev/videos";

export const projects = [
  {
    id: "apprend-moi-a-voler",
    title: "Apprend moi a voler",
    category: "Mini film RS",
    categories: ["Mini film RS", "IA Générative", "VFX / Compositing"],
    year: "2026",
    role: "Direction artistique / VFX",
    thumbnail: "./assets/thumbnails/apprend-moi-a-voler.webp?v=20260608-media-v27",
    tags: ["Mini film RS", "IA générative", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/apprend-moi-a-voler.mp4`,
  },
  {
    id: "def-hyper-espace",
    title: "DEF HYPER ESPACE",
    category: "VFX / Compositing",
    categories: ["VFX / Compositing", "Motion Design"],
    year: "2026",
    role: "VFX / 3D / Direction artistique",
    thumbnail: "./assets/thumbnails/def-hyper-espace.webp?v=20260608-media-v27",
    tags: ["VFX compositing", "3D", "Motion design"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/def-hyper-espace.mp4`,
  },
  {
    id: "mon-oncle",
    title: "Mon Oncle",
    category: "Mini film RS",
    categories: ["Mini film RS", "VFX / Compositing"],
    year: "2026",
    role: "Direction artistique / Montage",
    thumbnail: "./assets/thumbnails/mon-oncle.webp?v=20260608-media-v27",
    tags: ["Mini film RS", "Captation réelle", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/mon-oncle.mp4`,
  },
  {
    id: "nikita",
    title: "Nikita",
    category: "Mini film RS",
    categories: ["Mini film RS", "IA Générative", "VFX / Compositing"],
    year: "2026",
    role: "Direction artistique / IA générative",
    thumbnail: "./assets/thumbnails/nikita.webp?v=20260608-media-v27",
    tags: ["Mini film RS", "IA générative", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/nikita.mp4`,
  },
  {
    id: "lumen",
    title: "MOOD",
    category: "Mini film RS",
    categories: ["Mini film RS", "IA Générative"],
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/lumen.webp?v=20260604-final-cta",
    tags: ["Mini film RS", "IA générative"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/danse-reel-v01-insta-2.mp4`,
  },
  {
    id: "orbit",
    title: "Magic Candy",
    category: "IA Générative",
    categories: ["Mini film RS", "IA Générative", "Motion Design"],
    year: "2026",
    role: "Direction artistique / IA générative",
    thumbnail: "./assets/thumbnails/orbit.webp?v=20260604-final-cta",
    tags: ["Mini film RS", "IA générative", "Motion design"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/magic-candy-v01.mp4`,
  },
  {
    id: "rendez-vous",
    title: "Big bang, mon amour",
    category: "VFX / Compositing",
    categories: ["Mini film RS", "IA Générative", "VFX / Compositing"],
    year: "2026",
    role: "Captation réelle / IA générative / VFX",
    thumbnail: "./assets/thumbnails/rendez-vous.webp?v=20260604-final-cta",
    tags: ["Mini film RS", "Captation réelle", "IA générative", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/big-bang-x-juliard-v02.mp4`,
  },
  {
    id: "souvenirs",
    title: "Lord Esperanza x Pilot",
    category: "Mini film RS",
    categories: ["Mini film RS", "IA Générative", "VFX / Compositing"],
    year: "2026",
    role: "Direction artistique / Motion design",
    thumbnail: "./assets/thumbnails/souvenirs.webp?v=20260604-final-cta",
    tags: ["Mini film RS", "Captation réelle", "IA générative", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/en-boucle-x-pilot-ep-01.mov`,
  },
  {
    id: "interface",
    title: "Happy New Year",
    category: "Mini film RS",
    categories: ["Mini film RS", "IA Générative"],
    year: "2026",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/interface.webp?v=20260604-final-cta",
    tags: ["Mini film RS", "IA générative"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/new-year-2026.mp4`,
  },
  {
    id: "neoforma",
    title: "La recette du jour",
    category: "VFX / Compositing",
    categories: ["IA Générative", "VFX / Compositing"],
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/neoforma.webp?v=20260604-final-cta",
    tags: ["Captation réelle", "IA générative", "VFX compositing"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/la-recette-x-juliard.mp4`,
  },
  {
    id: "epure",
    title: "Generative",
    category: "Identité visuelle",
    categories: ["Motion Design", "IA Générative"],
    year: "2026",
    role: "Design graphique",
    thumbnail: "./assets/thumbnails/epure.webp?v=20260604-final-cta",
    tags: ["Motion design", "IA générative"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/reel-generatif-martin.mp4`,
  },
  {
    id: "domaine-paul-mas",
    title: "Domaine Paul Mas",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/domaine-paul-mas.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/domaine-paul-mas.mp4`,
  },
  {
    id: "edf-chooz",
    title: "EDF Chooz",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/edf-chooz.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/edf-chooz.mp4`,
  },
  {
    id: "engie-solution",
    title: "Engie Solutions",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/engie-solution.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/engie-solution.mp4`,
  },
  {
    id: "orange-ilomba",
    title: "Orange Ilomba",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/orange-ilomba.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/orange-ilomba.mp4`,
  },
  {
    id: "sib",
    title: "SIB",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/sib.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/sib.mp4`,
  },
  {
    id: "talent-soft",
    title: "Talent Soft",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/talent-soft.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/talent-soft.mp4`,
  },
  {
    id: "webhelp",
    title: "WebHelp",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/webhelp.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/webhelp.mp4`,
  },
  {
    id: "woah",
    title: "Woah",
    category: "Motion Design",
    categories: ["Motion Design"],
    year: "2024",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/woah.webp?v=20260604-final-cta",
    tags: ["Motion design"],
    featured: false,
    videoUrl: `${mediaBaseUrl}/woah.mp4`,
  },
];
