const mediaBaseUrl = "https://martin-motion-media.martinbarbe09.workers.dev/videos";

export const projects = [
  {
    id: "lumen",
    title: "Lumen",
    category: "Film",
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/lumen.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/danse-reel-v01-insta-2.mp4`,
  },
  {
    id: "orbit",
    title: "Orbit",
    category: "Experimentation",
    year: "2026",
    role: "Direction artistique / IA generative",
    thumbnail: "./assets/thumbnails/orbit.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/magic-candy-v01.mp4`,
  },
  {
    id: "rendez-vous",
    title: "Rendez-vous",
    category: "Animation 3D",
    year: "2026",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/rendez-vous.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/big-bang-x-juliard-v02.mp4`,
  },
  {
    id: "souvenirs",
    title: "Souvenirs",
    category: "Film",
    year: "2026",
    role: "Direction artistique / Motion design",
    thumbnail: "./assets/thumbnails/souvenirs.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/en-boucle-x-pilot-ep-01.mov`,
  },
  {
    id: "interface",
    title: "Interface",
    category: "Animation 2D",
    year: "2026",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/interface.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/new-year-2026.mp4`,
  },
  {
    id: "neoforma",
    title: "Neoforma",
    category: "Branding",
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/neoforma.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/la-recette-x-juliard.mp4`,
  },
  {
    id: "epure",
    title: "Epure",
    category: "Graphisme",
    year: "2026",
    role: "Design graphique",
    thumbnail: "./assets/thumbnails/epure.webp?v=20260602-hero-balance5",
    videoUrl: `${mediaBaseUrl}/reel-generatif-martin.mp4`,
  },
];
