const mediaBaseUrl = "https://martin-motion-media.martinbarbe09.workers.dev/videos";

export const projects = [
  {
    id: "lumen",
    title: "MOOD",
    category: "Mini Films",
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/lumen.webp?v=20260604-taxonomy",
    tags: ["Captation réelle", "Montage"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/danse-reel-v01-insta-2.mp4`,
  },
  {
    id: "orbit",
    title: "Magic Candy",
    category: "IA Générative",
    year: "2026",
    role: "Direction artistique / IA générative",
    thumbnail: "./assets/thumbnails/orbit.webp?v=20260604-taxonomy",
    tags: ["IA générative", "Motion design"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/magic-candy-v01.mp4`,
  },
  {
    id: "rendez-vous",
    title: "Big bang, mon amour",
    category: "VFX / Compositing",
    year: "2026",
    role: "Captation réelle / IA générative / VFX",
    thumbnail: "./assets/thumbnails/rendez-vous.webp?v=20260604-taxonomy",
    tags: ["Captation réelle", "IA générative", "VFX"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/big-bang-x-juliard-v02.mp4`,
  },
  {
    id: "souvenirs",
    title: "Lord Esperanza x Pilot",
    category: "Mini Films",
    year: "2026",
    role: "Direction artistique / Motion design",
    thumbnail: "./assets/thumbnails/souvenirs.webp?v=20260604-taxonomy",
    tags: ["IA générative", "Montage"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/en-boucle-x-pilot-ep-01.mov`,
  },
  {
    id: "interface",
    title: "Happy New Year",
    category: "Motion Design",
    year: "2026",
    role: "Motion design",
    thumbnail: "./assets/thumbnails/interface.webp?v=20260604-taxonomy",
    tags: ["Animation 2D", "Illustration"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/new-year-2026.mp4`,
  },
  {
    id: "neoforma",
    title: "La recette du jour",
    category: "Mini Films",
    year: "2026",
    role: "Direction artistique",
    thumbnail: "./assets/thumbnails/neoforma.webp?v=20260604-taxonomy",
    tags: ["Captation réelle", "Montage"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/la-recette-x-juliard.mp4`,
  },
  {
    id: "epure",
    title: "Generative",
    category: "Identité visuelle",
    year: "2026",
    role: "Design graphique",
    thumbnail: "./assets/thumbnails/epure.webp?v=20260604-taxonomy",
    tags: ["Illustration", "Motion design"],
    featured: true,
    videoUrl: `${mediaBaseUrl}/reel-generatif-martin.mp4`,
  },
];
